language: php

env:
    - SYMFONY_VERSION=2.3
    - SYMFONY_VERSION=2.4
    - SYMFONY_VERSION=2.5

before_script:
    - composer install --prefer-source

install:
    - composer require symfony/symfony:${SYMFONY_VERSION}.*@dev --no-update

script:
    - phpunit --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm
